x-deploy: &x-deploy
  replicas: ${RABBITMQ_REPLICAS:-3}
  placement:
    constraints:
      - node.labels.rabbitmq == true
  update_config:
    parallelism: 1
    failure_action: rollback
    delay: 30s
    order: stop-first
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-logging: &x-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  rabbitmq:

volumes:
  rabbitmq:

configs:
  enabled_plugins:
    file: configs/enabled_plugins
  rabbitmq.conf:
    template_driver: golang
    file: configs/rabbitmq.conf
  peer-discovery-consul.conf:
    template_driver: golang
    file: configs/peer-discovery-consul.conf

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:?Please set RABBITMQ_VERSION environment variable}-management-alpine
    hostname: rabbitmq-{{.Task.Slot}}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-erlang-cookie-{{.Service.Name}}}
      # Consul configuration
      CONSUL_HTTP_ADDR: ${CONSUL_HTTP_ADDR:-consul}
      CONSUL_HTTP_PORT: ${CONSUL_HTTP_PORT:-8500}
      CONSUL_HTTP_SCHEME: ${CONSUL_HTTP_SCHEME:-http}
      CONSUL_SERVICE_NAME: ${CONSUL_SERVICE_NAME:-{{.Service.Name}}}
      CONSUL_ACL_TOKEN: ${CONSUL_ACL_TOKEN}
    networks:
      - rabbitmq
    ports:
      - 4369:4369 # epmd peer discovery service
      - 5671:5671 # AMQPS Port
      - 5672:5672 # AMQP Port
      - 15672:15672 # Management UI port
      - 15692:15692 # Prometheus metrics (only if the Prometheus plugin is enabled)
    configs:
      - source: enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq.conf
        target: /etc/rabbitmq/conf.d/10-defaults.conf
      - source: peer-discovery-consul.conf
        target: /etc/rabbitmq/conf.d/peer-discovery-consul.conf
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy: *x-deploy
    logging: *x-logging
      
